### ISSUE TITLE
YAML Generation Tool

### ISSUE THREAD

**Issue by boogiespook** [instructlab/community#260]
For people who aren't YAML gurus (or new to YAML and just have problems with the correct indentation) I've written a very small app which can help create their first qna file. 

You just add in your Github name, skill name and 5 q & A and it will create the YAML for you in the correct format. Would be great to get it added as an InstructLab tool [YAML Generator](https://github.com/boogiespook/instructlab-yaml-generator)

The app doesn't save or log any data at all so no worries about data security.

**Comment by lhawthorn** [comment]
Thank you very much for creating this tool and sharing it with all of us @boogiespook! I have shared it with several maintainers and right now we are trying to determine the best way to use it, e.g. link to it in the documentation, ask you about forking and making a sanctioned tool for the project, something else entirely. We're probably going to think it through for a bit, but did not want you to think that we are not thankful nor that we have not been taking a look at it.

Appreciate you!

**Comment by boogiespook** [comment]
Thanks very much @lhawthorn and team :-) I'm more than happy to 'donate' it to the community!

**Comment by lhawthorn** [comment]
There are apparently 4 tools currently being developed and explored to determine how we should help our users create YAML files. Viva open source!

@boogiespook There are some additional constraints around what is required for said YAML generators that I fully understood during yesterday's triage meeting, but now that I've had some sleep I cannot recall them in detail.

I have also looked at the [daily triage meeting notes](https://docs.google.com/document/d/17GYyhjNGazRjWirSxJPTX7n-Qc1pXcxdNJYZGuTO_E0/edit#heading=h.840gvtl8qgyr) for 29 May 2024 and see that this information was not captured, so I shall endeavor to do a better job in the future of writing stuff down I know is important to share.

@jjasghar Would you be so kind as to quickly summarize the needs for YAML generation and why, turns out, what seems to be a relatively simple question (how do we help the nice people who write no YAML more easily use InstructLab?) is not so simple? IIRC, the deal was that we need a YAML generator that speaks smoothly to the InstructLab backend, but that may be me misremembering and is also overly simplistic for those nice contributors who may wish to help us with our current YAMLing processes.  Thank you kindly, JJ.

**Comment by jjasghar** [comment]
Closed per the github.com/instructlab/ui work that is happening.
